version: '3.3'

services:
  back-end:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend

    volumes:
      - ./backend/media:/home/app/web/media
    command: >
      python manage.py runserver 0.0.0.0:8000 --noreload
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.gateway
    volumes:
      - ./backend/static:/home/app/web/static
    ports:
      - "80:80"
    depends_on:
      - back-end

  front:
    build:
      context: ../shaar
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    hostname: 'shaar'

  db:
    image: postgres:15.1-alpine3.17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data/
    env_file:
      - ./backend/.env

volumes:
  static_volume:
  media_volume:
  postgres_data: