# Generated by Django 5.1.3 on 2024-11-21 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('avg_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Средняя цена')),
                ('avg_rating', models.FloatField(default=0, verbose_name='Средний рейтинг')),
                ('coordinates_x', models.FloatField(default=0, verbose_name='Координаты X')),
                ('coordinates_y', models.FloatField(default=0, verbose_name='Координаты Y')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('whatsapp', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('categories', models.ManyToManyField(related_name='places', to='place.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
