# Generated by Django 5.1.3 on 2024-11-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/images/', verbose_name='Изображение')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='images',
            field=models.ManyToManyField(related_name='images', to='place.placeimage'),
        ),
    ]
